from enum import StrEnum


class RecoveryStatus(StrEnum):
    DETECTED = "DETECTED"
    CONTEXT_BUILDING = "CONTEXT_BUILDING"
    ANALYZING = "ANALYZING"
    DIAGNOSED = "DIAGNOSED"
    ECONOMICALLY_EVALUATED = "ECONOMICALLY_EVALUATED"
    DECISION_PENDING = "DECISION_PENDING"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    POLICY_CHECK = "POLICY_CHECK"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    NO_ACTION = "NO_ACTION"
    NOT_RECOVERABLE = "NOT_RECOVERABLE"
    ESCALATED = "ESCALATED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"
